### ISSUE TITLE
ArgumentError in RocketJobMissionControl::JobsController#index

### ISSUE THREAD

**Issue by MatUrbanski** [rocketjob/rocketjob_mission_control#18]
Hi, I have the following error when trying to visit /rocketjob:

```
  ArgumentError in RocketJobMissionControl::JobsController#index wrong number of arguments (2 for 0..1)
```

```
Completed 500 Internal Server Error in 209ms (ActiveRecord: 0.0ms)

ArgumentError (wrong number of arguments (2 for 0..1)):
  /home/mateusz/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/logger.rb:451:in `error'
  rocketjob_mission_control (1.2.1) app/controllers/rocket_job_mission_control/jobs_controller.rb:91:in `error_occurred'

```
My rails version is 4.2.4.

**Comment by reidmorrison** [comment]
Hi Mateusz,

It appears RJMC is using the extended logging API that is part of Rails Semantic Logger.

We have 2 options:

1. Install the gem `rails_semantic_logger`
2. Change RJMC to not use the extended logging API.

The quickest solution is to add the following line to the Gemfile:
```ruby
gem 'rails_semantic_logger'
```

Semantic Logger is a dependency for RocketJob, we do not mandate Rails Semantic Logger for the Rails application since it replaces the default Rails logger. If replacing the existing logger is not an issue for you, please try adding the gem entry above and then run `bundle`.

Let us know if you like the resulting log output from Rails Semantic Logger. In the meantime we will research the option of using the standard Rails logger.

There are also many benefits to switching the Rails app to [Semantic Logger](http://reidmorrison.github.io/semantic_logger/).

**Comment by reidmorrison** [comment]
I noticed the RJMC installation instructions skip over the mongo setup, please checkout also the Rails installation instructions to also ensure that mongoDB is configured appropriately:
[Configuration](http://rocketjob.io/configuration.html)

**Comment by MatUrbanski** [comment]
Adding ```gem 'rails_semantic_logger``` to Gemfile solves the problem. Semantic Logger is pretty nice. Thank's for help.
